//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class logmessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal logmessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service.logmessages", typeof(logmessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception was caught while disposing.
        /// </summary>
        internal static string ServiceExceptionDispose
        {
            get
            {
                return ResourceManager.GetString("ServiceExceptionDispose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The service is initialised.
        /// </summary>
        internal static string ServiceInitialised
        {
            get
            {
                return ResourceManager.GetString("ServiceInitialised", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service call OnContinue().
        /// </summary>
        internal static string ServiceOnContinue
        {
            get
            {
                return ResourceManager.GetString("ServiceOnContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service call OnPause().
        /// </summary>
        internal static string ServiceOnPause
        {
            get
            {
                return ResourceManager.GetString("ServiceOnPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service call OnShutdown().
        /// </summary>
        internal static string ServiceOnShutdown
        {
            get
            {
                return ResourceManager.GetString("ServiceOnShutdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service call OnStart().
        /// </summary>
        internal static string ServiceOnStart
        {
            get
            {
                return ResourceManager.GetString("ServiceOnStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service call OnStop().
        /// </summary>
        internal static string ServiceOnStop
        {
            get
            {
                return ResourceManager.GetString("ServiceOnStop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The service is now paused.
        /// </summary>
        internal static string ServicePaused
        {
            get
            {
                return ResourceManager.GetString("ServicePaused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All signals have been reset.
        /// </summary>
        internal static string ServiceSignalsReset
        {
            get
            {
                return ResourceManager.GetString("ServiceSignalsReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finished waiting, all signals are set.
        /// </summary>
        internal static string ServiceSignalsSet
        {
            get
            {
                return ResourceManager.GetString("ServiceSignalsSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting for signals....
        /// </summary>
        internal static string ServiceSignalsWait
        {
            get
            {
                return ResourceManager.GetString("ServiceSignalsWait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The service is now stopped.
        /// </summary>
        internal static string ServiceStopped
        {
            get
            {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception was caught at the top of the worker stack.
        /// </summary>
        internal static string WorkerException
        {
            get
            {
                return ResourceManager.GetString("WorkerException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: OnContinue() with id {0} on thread id {1}.
        /// </summary>
        internal static string WorkerOnContinue
        {
            get
            {
                return ResourceManager.GetString("WorkerOnContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception occurred calling OnContinue().
        /// </summary>
        internal static string WorkerOnContinueException
        {
            get
            {
                return ResourceManager.GetString("WorkerOnContinueException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: OnPause() with id {0} on thread id {1}.
        /// </summary>
        internal static string WorkerOnPause
        {
            get
            {
                return ResourceManager.GetString("WorkerOnPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception occurred calling OnPause().
        /// </summary>
        internal static string WorkerOnPauseException
        {
            get
            {
                return ResourceManager.GetString("WorkerOnPauseException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: OnShutdown() with id {0} on thread id {1}.
        /// </summary>
        internal static string WorkerOnShutdown
        {
            get
            {
                return ResourceManager.GetString("WorkerOnShutdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception occurred calling OnShutdown().
        /// </summary>
        internal static string WorkerOnShutdownException
        {
            get
            {
                return ResourceManager.GetString("WorkerOnShutdownException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: OnStop() with id {0} on thread id {1}.
        /// </summary>
        internal static string WorkerOnStop
        {
            get
            {
                return ResourceManager.GetString("WorkerOnStop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception occurred calling OnStop().
        /// </summary>
        internal static string WorkerOnStopException
        {
            get
            {
                return ResourceManager.GetString("WorkerOnStopException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An exception occurred called Work().
        /// </summary>
        internal static string WorkerOnWorkException
        {
            get
            {
                return ResourceManager.GetString("WorkerOnWorkException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: Work() with id {0} on thread id {1} duration = {2}.
        /// </summary>
        internal static string WorkerWorkDuration
        {
            get
            {
                return ResourceManager.GetString("WorkerWorkDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: Work() call with id {0} on thread id {1} entered at {2}.
        /// </summary>
        internal static string WorkerWorkEnter
        {
            get
            {
                return ResourceManager.GetString("WorkerWorkEnter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker: Work() call with id {0} on thread id {1} exited at {2}.
        /// </summary>
        internal static string WorkerWorkExit
        {
            get
            {
                return ResourceManager.GetString("WorkerWorkExit", resourceCulture);
            }
        }
    }
}
