-
    branches:
        only:
            - master
            - dev
    configuration: Release
    platform: win7-x64

    build_script:
        - dotnet build "src\Service\" -c %CONFIGURATION% -r %PLATFORM%
    
    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

    test_script:
        - dotnet test "tests\LicenseMonitoringSystem.Tests" -c %CONFIGURATION%
            

- 
    branches:
        only:
            - /feature/.*/
    configuration: Release
    platform: win7-x64

    build_script:
        - dotnet build "src\Service\" -c %CONFIGURATION% -r %PLATFORM%
    
    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

    test_script:
        - dotnet test "tests\LicenseMonitoringSystem.Tests" -c %CONFIGURATION%

-
    branches:
        only:
            - /.*/merge/
    configuration: Release
    platform: win7-x64

    build_script:
        - dotnet build "src\Service\" -c %CONFIGURATION% -r %PLATFORM%

    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

    test_script:
        - dotnet test "tests\LicenseMonitoringSystem.Tests" -c %CONFIGURATION%