#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic

#---------------------------------#
# Tests
#---------------------------------#

test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  only:
    - master
    - dev
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- src\packages -> src\**\packages.config

#---------------------------------#
#    environment configuration    #
#---------------------------------#

hosts:
    api.nuget.org: 93.184.221.200

# environment variables
environment:
    GITHUB_USERNAME:
        secure: 5/1fTn1ujG9fgBeJU0NFbA==
    GITHUB_PASSWORD:
        secure: uminGVAG8/kES/o/cXSqnnAtqxy8bSzj6qdlpITVzLo=
    APPVEYOR_API_TOKEN:
        secure: bv3OAkxTvWkMKa10ZThe0yv0SjwX1bjh/Yfvq1gjkiU=