#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - master
    - dev

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  GitHubUserName:
    secure: 5/1fTn1ujG9fgBeJU0NFbA==
  GitHubPassword:
    secure: uminGVAG8/kES/o/cXSqnnAtqxy8bSzj6qdlpITVzLo=
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\BuildScripts\build.ps1
  
test:
    assemblies:
        -'**\*.Tests.dll'

#---------------------------------#
#      caching configuration      #
#---------------------------------#

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

#---------------------------------#
#  notifications configuration    #
#---------------------------------#