#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -Target AppVeyor

#---------------------------------#
# Tests
#---------------------------------#

test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  only:
    - master
    - dev
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- src\packages -> src\**\packages.config

#---------------------------------#
#    environment configuration    #
#---------------------------------#

hosts:
    api.nuget.org: 93.184.221.200

# environment variables
environment:
  GitHubUserName:
    secure: 5/1fTn1ujG9fgBeJU0NFbA==
  GitHubPassword:
    secure: uminGVAG8/kES/o/cXSqnnAtqxy8bSzj6qdlpITVzLo=