install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

build:
  project: LicenseMonitoringSystem.sln