-
    branches:
        only:
            - master
            - dev

    image: Visual Studio 2017

    configuration: Release

    build:
        project: LicenseMonitoringSystem.sln
        verbosity: minimal
    
    install:
        - choco install gitversion.portable -pre -y       

    before_build:
        - ps: nuget restore
        - ps: dotnet restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

    test:
        assemblies: 
            - '**\*.Tests.dll'

    artifacts: 
        - path: src\Bootstrapper\bin\$(configuration)\*.exe
          name: setup

    deploy:
        release: v$(GitVersion_FullSemVer)
        description: insert description
        provider: GitHub
        auth_token:
            secure: iAL0fibu0a8mOfti5EphBezFTZ1j1QDS439gkSJgRTEyGe8Smr1maQYwNMrOZosA
        artifact: setup
        draft: false
        prerelease: false
        on:
            appveyor_repo_tag: true

- 
    branches:
        only:
            - /feature/.*/

    image: Visual Studio 2017

    configuration: Release

    build:
        project: LicenseMonitoringSystem.sln.
        verbosity: minimal
    
    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: dotnet restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

    test:
        assemblies: 
            - '**\*.Tests.dll'

-
    branches:
        only:
            - /release/.*/

    image: Visual Studio 2017

    configuration: Release

    build:
        project: LicenseMonitoringSystem.sln
        verbosity: minimal

    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: dotnet restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

    test:
        assemblies: 
            - '**\*.Tests.dll'