-
    branches:
        only:
            - master
            - dev
    configuration: Release

    build:
        parallel: true
        project: LicenseMonitoringSystem.sln
    
    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH


- 
    branches:
        only:
            - /feature/.*/
    configuration: Release

    build:
        parallel: true
        project: LicenseMonitoringSystem.sln
    
    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH


-
    branches:
        only:
            - /.*/merge/
    configuration: Release

    build:
        parallel: true
        project: LicenseMonitoringSystem.sln

    install:
        - choco install gitversion.portable -pre -y

    before_build:
        - ps: nuget restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH