#---------------------------------#
#           master branch         #
#---------------------------------#
-
    branches:
        only:
            - master

# environment configuration
    image: Visual Studio 2017
    cache:
        - packages -> **\packages.config
        - '%LocalAppData%\NuGet\Cache'

    install:
        - choco install gitversion.portable -pre -y    

# build configuration
    configuration: Release
    matrix:
        fast_finish: true

    build:
        parallel: true
        project: LicenseMonitoringSystem.sln
        verbosity: minimal    

    before_build:
        - ps: nuget restore
        - ps: dotnet restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

# test configuration
    test:
        assemblies: 
            - '**\*.Tests.dll'

# artifacts configuration
    artifacts: 
        - path: src\Installer\bin\$(configuration)\LMS.exe
          name: setup

# deployment configuration
    deploy:
        release: v$(GitVersion_FullSemVer)
        description: insert description
        provider: GitHub
        auth_token:
            secure: iAL0fibu0a8mOfti5EphBezFTZ1j1QDS439gkSJgRTEyGe8Smr1maQYwNMrOZosA
        artifact: setup
        draft: false
        prerelease: false
        on:
            appveyor_repo_tag: true

#---------------------------------#
#      release/hotfix branches    #
#---------------------------------#
- 
    branches:
        only:
            - /release/.*/
            - /feature/.*/

# environment configuration
    image: Visual Studio 2017
    cache:
        - packages -> **\packages.config
        - '%LocalAppData%\NuGet\Cache'

    install:
        - choco install gitversion.portable -pre -y

# build configuration
    configuration: Release
    matrix:
        fast_finish: true

    build:
        parallel: true
        project: LicenseMonitoringSystem.sln.
        verbosity: minimal
    
    before_build:
        - ps: nuget restore
        - ps: dotnet restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

# test configuration
    test:
        assemblies: 
            - '**\*.Tests.dll'

#---------------------------------#
#          other branches         #
#---------------------------------#
-
    branches:
        except:
            - master
            - /release/.*/
            - /hotfix/.*/

# environment configuration
    image: Visual Studio 2017
    cache:
        - packages -> **\packages.config
        - '%LocalAppData%\NuGet\Cache'

    install:
        - choco install gitversion.portable -pre -y

# build configuration
    configuration: Release
    matrix:
        fast_finish: true

    build:
        parallel: true
        project: LicenseMonitoringSystem.sln.
        verbosity: minimal
    
    before_build:
        - ps: nuget restore
        - ps: dotnet restore
        - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

# test configuration
    test:
        assemblies: 
            - '**\*.Tests.dll'