#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -Target AppVeyor

#---------------------------------#
# Tests
#---------------------------------#

test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- src\packages -> src\**\packages.config
- tools -> setup.cake