#---------------------------------#
#  Shared Configuration           #
#---------------------------------#
image: Visual Studio 2017

test: off

cache:
- src\packages -> src\**\packages.config

environment:
    GITHUB_USERNAME:
        secure: 5/1fTn1ujG9fgBeJU0NFbA==
    GITHUB_PASSWORD:
        secure: uminGVAG8/kES/o/cXSqnnAtqxy8bSzj6qdlpITVzLo=
    APPVEYOR_API_TOKEN:
        secure: bv3OAkxTvWkMKa10ZThe0yv0SjwX1bjh/Yfvq1gjkiU=
    CODECOV_REPO_TOKEN:
        secure: 7eQZghNqRnwThS9R9qZ46YZL4j1wDXEBA1l7lTOQ6QxtWBZFv4VxLA52qIV1FPmc

#---------------------------------#
#  Branch Specific Configuration  #
#---------------------------------#

for:
-
    branches:
        only:
            - master

    skip_tags: true

    build_script:
        - ps: .\build.ps1 -Target ReleaseNotes

-
    branches:
        only:
            - master

    skip_non_tags: true

    build_script:
        - ps: .\build.ps1 -Target AppVeyor

-
    branches:
        only:
            - dev

    build_script:
        - ps: .\build.ps1 -Target AppVeyor

-
    branches:
        only:
            - /release/.*/
            - /hotfix/.*/

    build_script:
        - ps: .\build.ps1