//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05/04/2018 15:32:13
namespace Portal.LicenseMonitoringSystem.Users.Entities
{
    /// <summary>
    /// There are no comments for LicenseUserSingle in the schema.
    /// </summary>
    public partial class LicenseUserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LicenseUser>
    {
        /// <summary>
        /// Initialize a new LicenseUserSingle object.
        /// </summary>
        public LicenseUserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LicenseUserSingle object.
        /// </summary>
        public LicenseUserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LicenseUserSingle object.
        /// </summary>
        public LicenseUserSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LicenseUser> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for LicenseUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class LicenseUser : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LicenseUser object.
        /// </summary>
        /// <param name="enabled">Initial value of Enabled.</param>
        /// <param name="managedSupportId">Initial value of ManagedSupportId.</param>
        /// <param name="userType">Initial value of UserType.</param>
        /// <param name="whenCreated">Initial value of WhenCreated.</param>
        /// <param name="isDeleted">Initial value of IsDeleted.</param>
        /// <param name="tenantId">Initial value of TenantId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static LicenseUser CreateLicenseUser(bool enabled, 
                    int managedSupportId, 
                    global::Portal.LicenseMonitoringSystem.Users.Entities.UserType userType, 
                    global::System.DateTimeOffset whenCreated, 
                    bool isDeleted, 
                    int tenantId, 
                    global::System.Guid ID)
        {
            LicenseUser licenseUser = new LicenseUser();
            licenseUser.Enabled = enabled;
            licenseUser.ManagedSupportId = managedSupportId;
            licenseUser.UserType = userType;
            licenseUser.WhenCreated = whenCreated;
            licenseUser.IsDeleted = isDeleted;
            licenseUser.TenantId = tenantId;
            licenseUser.Id = ID;
            return licenseUser;
        }
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("DisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Enabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool Enabled
        {
            get
            {
                return this._Enabled;
            }
            set
            {
                this.OnEnabledChanging(value);
                this._Enabled = value;
                this.OnEnabledChanged();
                this.OnPropertyChanged("Enabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _Enabled;
        partial void OnEnabledChanging(bool value);
        partial void OnEnabledChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastLoginDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> LastLoginDate
        {
            get
            {
                return this._LastLoginDate;
            }
            set
            {
                this.OnLastLoginDateChanging(value);
                this._LastLoginDate = value;
                this.OnLastLoginDateChanged();
                this.OnPropertyChanged("LastLoginDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastLoginDate;
        partial void OnLastLoginDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastLoginDateChanged();
        /// <summary>
        /// There are no comments for Property ManagedSupportId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int ManagedSupportId
        {
            get
            {
                return this._ManagedSupportId;
            }
            set
            {
                this.OnManagedSupportIdChanging(value);
                this._ManagedSupportId = value;
                this.OnManagedSupportIdChanged();
                this.OnPropertyChanged("ManagedSupportId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _ManagedSupportId;
        partial void OnManagedSupportIdChanging(int value);
        partial void OnManagedSupportIdChanged();
        /// <summary>
        /// There are no comments for Property SamAccountName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string SamAccountName
        {
            get
            {
                return this._SamAccountName;
            }
            set
            {
                this.OnSamAccountNameChanging(value);
                this._SamAccountName = value;
                this.OnSamAccountNameChanged();
                this.OnPropertyChanged("SamAccountName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _SamAccountName;
        partial void OnSamAccountNameChanging(string value);
        partial void OnSamAccountNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
                this.OnPropertyChanged("Surname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property UserType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Portal.LicenseMonitoringSystem.Users.Entities.UserType UserType
        {
            get
            {
                return this._UserType;
            }
            set
            {
                this.OnUserTypeChanging(value);
                this._UserType = value;
                this.OnUserTypeChanged();
                this.OnPropertyChanged("UserType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Portal.LicenseMonitoringSystem.Users.Entities.UserType _UserType;
        partial void OnUserTypeChanging(global::Portal.LicenseMonitoringSystem.Users.Entities.UserType value);
        partial void OnUserTypeChanged();
        /// <summary>
        /// There are no comments for Property WhenCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset WhenCreated
        {
            get
            {
                return this._WhenCreated;
            }
            set
            {
                this.OnWhenCreatedChanging(value);
                this._WhenCreated = value;
                this.OnWhenCreatedChanged();
                this.OnPropertyChanged("WhenCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _WhenCreated;
        partial void OnWhenCreatedChanging(global::System.DateTimeOffset value);
        partial void OnWhenCreatedChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsDeleted;
        partial void OnIsDeletedChanging(bool value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
                this.OnPropertyChanged("TenantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TenantId;
        partial void OnTenantIdChanging(int value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LicenseGroupSingle in the schema.
    /// </summary>
    public partial class LicenseGroupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LicenseGroup>
    {
        /// <summary>
        /// Initialize a new LicenseGroupSingle object.
        /// </summary>
        public LicenseGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LicenseGroupSingle object.
        /// </summary>
        public LicenseGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LicenseGroupSingle object.
        /// </summary>
        public LicenseGroupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LicenseGroup> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for LicenseGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class LicenseGroup : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LicenseGroup object.
        /// </summary>
        /// <param name="whenCreated">Initial value of WhenCreated.</param>
        /// <param name="isDeleted">Initial value of IsDeleted.</param>
        /// <param name="tenantId">Initial value of TenantId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static LicenseGroup CreateLicenseGroup(global::System.DateTimeOffset whenCreated, bool isDeleted, int tenantId, global::System.Guid ID)
        {
            LicenseGroup licenseGroup = new LicenseGroup();
            licenseGroup.WhenCreated = whenCreated;
            licenseGroup.IsDeleted = isDeleted;
            licenseGroup.TenantId = tenantId;
            licenseGroup.Id = ID;
            return licenseGroup;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property WhenCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset WhenCreated
        {
            get
            {
                return this._WhenCreated;
            }
            set
            {
                this.OnWhenCreatedChanging(value);
                this._WhenCreated = value;
                this.OnWhenCreatedChanged();
                this.OnPropertyChanged("WhenCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _WhenCreated;
        partial void OnWhenCreatedChanging(global::System.DateTimeOffset value);
        partial void OnWhenCreatedChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsDeleted;
        partial void OnIsDeletedChanging(bool value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
                this.OnPropertyChanged("TenantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TenantId;
        partial void OnTenantIdChanging(int value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LicenseUserGroupSingle in the schema.
    /// </summary>
    public partial class LicenseUserGroupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LicenseUserGroup>
    {
        /// <summary>
        /// Initialize a new LicenseUserGroupSingle object.
        /// </summary>
        public LicenseUserGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LicenseUserGroupSingle object.
        /// </summary>
        public LicenseUserGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LicenseUserGroupSingle object.
        /// </summary>
        public LicenseUserGroupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LicenseUserGroup> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for LicenseUserGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// GroupId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserId", "GroupId")]
    public partial class LicenseUserGroup : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LicenseUserGroup object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="groupId">Initial value of GroupId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static LicenseUserGroup CreateLicenseUserGroup(global::System.Guid userId, global::System.Guid groupId)
        {
            LicenseUserGroup licenseUserGroup = new LicenseUserGroup();
            licenseUserGroup.UserId = userId;
            licenseUserGroup.GroupId = groupId;
            return licenseUserGroup;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _GroupId;
        partial void OnGroupIdChanging(global::System.Guid value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ManagedSupportSingle in the schema.
    /// </summary>
    public partial class ManagedSupportSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ManagedSupport>
    {
        /// <summary>
        /// Initialize a new ManagedSupportSingle object.
        /// </summary>
        public ManagedSupportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ManagedSupportSingle object.
        /// </summary>
        public ManagedSupportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ManagedSupportSingle object.
        /// </summary>
        public ManagedSupportSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ManagedSupport> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ManagedSupport in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class ManagedSupport : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ManagedSupport object.
        /// </summary>
        /// <param name="deviceId">Initial value of DeviceId.</param>
        /// <param name="checkInTime">Initial value of CheckInTime.</param>
        /// <param name="tenantId">Initial value of TenantId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ManagedSupport CreateManagedSupport(global::System.Guid deviceId, global::System.DateTimeOffset checkInTime, int tenantId, int ID)
        {
            ManagedSupport managedSupport = new ManagedSupport();
            managedSupport.DeviceId = deviceId;
            managedSupport.CheckInTime = checkInTime;
            managedSupport.TenantId = tenantId;
            managedSupport.Id = ID;
            return managedSupport;
        }
        /// <summary>
        /// There are no comments for Property DeviceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid DeviceId
        {
            get
            {
                return this._DeviceId;
            }
            set
            {
                this.OnDeviceIdChanging(value);
                this._DeviceId = value;
                this.OnDeviceIdChanged();
                this.OnPropertyChanged("DeviceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _DeviceId;
        partial void OnDeviceIdChanging(global::System.Guid value);
        partial void OnDeviceIdChanged();
        /// <summary>
        /// There are no comments for Property Hostname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Hostname
        {
            get
            {
                return this._Hostname;
            }
            set
            {
                this.OnHostnameChanging(value);
                this._Hostname = value;
                this.OnHostnameChanged();
                this.OnPropertyChanged("Hostname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Hostname;
        partial void OnHostnameChanging(string value);
        partial void OnHostnameChanged();
        /// <summary>
        /// There are no comments for Property IpAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string IpAddress
        {
            get
            {
                return this._IpAddress;
            }
            set
            {
                this.OnIpAddressChanging(value);
                this._IpAddress = value;
                this.OnIpAddressChanged();
                this.OnPropertyChanged("IpAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _IpAddress;
        partial void OnIpAddressChanging(string value);
        partial void OnIpAddressChanged();
        /// <summary>
        /// There are no comments for Property CheckInTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset CheckInTime
        {
            get
            {
                return this._CheckInTime;
            }
            set
            {
                this.OnCheckInTimeChanging(value);
                this._CheckInTime = value;
                this.OnCheckInTimeChanged();
                this.OnPropertyChanged("CheckInTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CheckInTime;
        partial void OnCheckInTimeChanging(global::System.DateTimeOffset value);
        partial void OnCheckInTimeChanged();
        /// <summary>
        /// There are no comments for Property ClientVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ClientVersion
        {
            get
            {
                return this._ClientVersion;
            }
            set
            {
                this.OnClientVersionChanging(value);
                this._ClientVersion = value;
                this.OnClientVersionChanged();
                this.OnPropertyChanged("ClientVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ClientVersion;
        partial void OnClientVersionChanging(string value);
        partial void OnClientVersionChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
                this.OnPropertyChanged("TenantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TenantId;
        partial void OnTenantIdChanging(int value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for UserType in the schema.
    /// </summary>
    [global::System.Flags]
    public enum UserType
    {
        New = 0,
        Active = 1,
        Inactive = 2,
        Central = 4,
        ThirdParty = 8,
        Admin = 16,
        Service = 32,
        Mailbox = 64
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser as global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser as global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup as global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup as global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup as global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup as global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="userId">The value of userId</param>
        /// <param name="groupId">The value of groupId</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup> source,
            global::System.Guid userId, 
            global::System.Guid groupId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserId", userId }, 
                { "GroupId", groupId }
            };
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport as global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupportSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupportSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport as global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupportSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupportSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Portal.LicenseMonitoringSystem.Veeam.Entities
{
    /// <summary>
    /// There are no comments for VeeamSingle in the schema.
    /// </summary>
    public partial class VeeamSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Veeam>
    {
        /// <summary>
        /// Initialize a new VeeamSingle object.
        /// </summary>
        public VeeamSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VeeamSingle object.
        /// </summary>
        public VeeamSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VeeamSingle object.
        /// </summary>
        public VeeamSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Veeam> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Veeam in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Veeam : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Veeam object.
        /// </summary>
        /// <param name="edition">Initial value of Edition.</param>
        /// <param name="expirationDate">Initial value of ExpirationDate.</param>
        /// <param name="hyperV">Initial value of HyperV.</param>
        /// <param name="licenseType">Initial value of LicenseType.</param>
        /// <param name="programVersion">Initial value of ProgramVersion.</param>
        /// <param name="vSphere">Initial value of vSphere.</param>
        /// <param name="isDeleted">Initial value of IsDeleted.</param>
        /// <param name="checkInTime">Initial value of CheckInTime.</param>
        /// <param name="tenantId">Initial value of TenantId.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Veeam CreateVeeam(global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseEditions edition, 
                    global::System.DateTimeOffset expirationDate, 
                    int hyperV, 
                    global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseTypeEx licenseType, 
                    string programVersion, 
                    int vSphere, 
                    bool isDeleted, 
                    global::System.DateTimeOffset checkInTime, 
                    int tenantId, 
                    bool isActive, 
                    global::System.Guid ID)
        {
            Veeam veeam = new Veeam();
            veeam.Edition = edition;
            veeam.ExpirationDate = expirationDate;
            veeam.HyperV = hyperV;
            veeam.LicenseType = licenseType;
            veeam.ProgramVersion = programVersion;
            veeam.vSphere = vSphere;
            veeam.IsDeleted = isDeleted;
            veeam.CheckInTime = checkInTime;
            veeam.TenantId = tenantId;
            veeam.IsActive = isActive;
            veeam.Id = ID;
            return veeam;
        }
        /// <summary>
        /// There are no comments for Property Edition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseEditions Edition
        {
            get
            {
                return this._Edition;
            }
            set
            {
                this.OnEditionChanging(value);
                this._Edition = value;
                this.OnEditionChanged();
                this.OnPropertyChanged("Edition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseEditions _Edition;
        partial void OnEditionChanging(global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseEditions value);
        partial void OnEditionChanged();
        /// <summary>
        /// There are no comments for Property ExpirationDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset ExpirationDate
        {
            get
            {
                return this._ExpirationDate;
            }
            set
            {
                this.OnExpirationDateChanging(value);
                this._ExpirationDate = value;
                this.OnExpirationDateChanged();
                this.OnPropertyChanged("ExpirationDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.DateTimeOffset value);
        partial void OnExpirationDateChanged();
        /// <summary>
        /// There are no comments for Property ExternalIpAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ExternalIpAddress
        {
            get
            {
                return this._ExternalIpAddress;
            }
            set
            {
                this.OnExternalIpAddressChanging(value);
                this._ExternalIpAddress = value;
                this.OnExternalIpAddressChanged();
                this.OnPropertyChanged("ExternalIpAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ExternalIpAddress;
        partial void OnExternalIpAddressChanging(string value);
        partial void OnExternalIpAddressChanged();
        /// <summary>
        /// There are no comments for Property Hostname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Hostname
        {
            get
            {
                return this._Hostname;
            }
            set
            {
                this.OnHostnameChanging(value);
                this._Hostname = value;
                this.OnHostnameChanged();
                this.OnPropertyChanged("Hostname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Hostname;
        partial void OnHostnameChanging(string value);
        partial void OnHostnameChanged();
        /// <summary>
        /// There are no comments for Property HyperV in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int HyperV
        {
            get
            {
                return this._HyperV;
            }
            set
            {
                this.OnHyperVChanging(value);
                this._HyperV = value;
                this.OnHyperVChanged();
                this.OnPropertyChanged("HyperV");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _HyperV;
        partial void OnHyperVChanging(int value);
        partial void OnHyperVChanged();
        /// <summary>
        /// There are no comments for Property LicenseType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseTypeEx LicenseType
        {
            get
            {
                return this._LicenseType;
            }
            set
            {
                this.OnLicenseTypeChanging(value);
                this._LicenseType = value;
                this.OnLicenseTypeChanged();
                this.OnPropertyChanged("LicenseType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseTypeEx _LicenseType;
        partial void OnLicenseTypeChanging(global::Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseTypeEx value);
        partial void OnLicenseTypeChanged();
        /// <summary>
        /// There are no comments for Property ProgramVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ProgramVersion
        {
            get
            {
                return this._ProgramVersion;
            }
            set
            {
                this.OnProgramVersionChanging(value);
                this._ProgramVersion = value;
                this.OnProgramVersionChanged();
                this.OnPropertyChanged("ProgramVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ProgramVersion;
        partial void OnProgramVersionChanging(string value);
        partial void OnProgramVersionChanged();
        /// <summary>
        /// There are no comments for Property SupportId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string SupportId
        {
            get
            {
                return this._SupportId;
            }
            set
            {
                this.OnSupportIdChanging(value);
                this._SupportId = value;
                this.OnSupportIdChanged();
                this.OnPropertyChanged("SupportId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _SupportId;
        partial void OnSupportIdChanging(string value);
        partial void OnSupportIdChanged();
        /// <summary>
        /// There are no comments for Property vSphere in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int vSphere
        {
            get
            {
                return this._vSphere;
            }
            set
            {
                this.OnvSphereChanging(value);
                this._vSphere = value;
                this.OnvSphereChanged();
                this.OnPropertyChanged("vSphere");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _vSphere;
        partial void OnvSphereChanging(int value);
        partial void OnvSphereChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsDeleted;
        partial void OnIsDeletedChanging(bool value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for Property DeletionTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> DeletionTime
        {
            get
            {
                return this._DeletionTime;
            }
            set
            {
                this.OnDeletionTimeChanging(value);
                this._DeletionTime = value;
                this.OnDeletionTimeChanged();
                this.OnPropertyChanged("DeletionTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DeletionTime;
        partial void OnDeletionTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeletionTimeChanged();
        /// <summary>
        /// There are no comments for Property DeleterUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<long> DeleterUserId
        {
            get
            {
                return this._DeleterUserId;
            }
            set
            {
                this.OnDeleterUserIdChanging(value);
                this._DeleterUserId = value;
                this.OnDeleterUserIdChanged();
                this.OnPropertyChanged("DeleterUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<long> _DeleterUserId;
        partial void OnDeleterUserIdChanging(global::System.Nullable<long> value);
        partial void OnDeleterUserIdChanged();
        /// <summary>
        /// There are no comments for Property CheckInTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset CheckInTime
        {
            get
            {
                return this._CheckInTime;
            }
            set
            {
                this.OnCheckInTimeChanging(value);
                this._CheckInTime = value;
                this.OnCheckInTimeChanged();
                this.OnPropertyChanged("CheckInTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CheckInTime;
        partial void OnCheckInTimeChanging(global::System.DateTimeOffset value);
        partial void OnCheckInTimeChanged();
        /// <summary>
        /// There are no comments for Property ClientVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string ClientVersion
        {
            get
            {
                return this._ClientVersion;
            }
            set
            {
                this.OnClientVersionChanging(value);
                this._ClientVersion = value;
                this.OnClientVersionChanged();
                this.OnPropertyChanged("ClientVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ClientVersion;
        partial void OnClientVersionChanging(string value);
        partial void OnClientVersionChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
                this.OnPropertyChanged("TenantId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TenantId;
        partial void OnTenantIdChanging(int value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this._IsActive = value;
                this.OnIsActiveChanged();
                this.OnPropertyChanged("IsActive");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LicenseEditions in the schema.
    /// </summary>
    public enum LicenseEditions
    {
        Standard = 0,
        Enterprise = 1,
        EnterprisePlus = 2
    }
    /// <summary>
    /// There are no comments for LicenseTypeEx in the schema.
    /// </summary>
    public enum LicenseTypeEx
    {
        Empty = 0,
        Evaluation = 1,
        Full = 2,
        NFR = 3,
        Perpetual = 4,
        Rental = 5,
        Subscription = 6
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam as global::Portal.LicenseMonitoringSystem.Veeam.Entities.VeeamSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Portal.LicenseMonitoringSystem.Veeam.Entities.VeeamSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Portal.LicenseMonitoringSystem.Veeam.Entities.VeeamSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam as global::Portal.LicenseMonitoringSystem.Veeam.Entities.VeeamSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Portal.LicenseMonitoringSystem.Veeam.Entities.VeeamSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Portal.LicenseMonitoringSystem.Veeam.Entities.VeeamSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser> _Users;
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup> Groups
        {
            get
            {
                if ((this._Groups == null))
                {
                    this._Groups = base.CreateQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup>("Groups");
                }
                return this._Groups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup> _Groups;
        /// <summary>
        /// There are no comments for UserGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup> UserGroups
        {
            get
            {
                if ((this._UserGroups == null))
                {
                    this._UserGroups = base.CreateQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup>("UserGroups");
                }
                return this._UserGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup> _UserGroups;
        /// <summary>
        /// There are no comments for ManagedServers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport> ManagedServers
        {
            get
            {
                if ((this._ManagedServers == null))
                {
                    this._ManagedServers = base.CreateQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport>("ManagedServers");
                }
                return this._ManagedServers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport> _ManagedServers;
        /// <summary>
        /// There are no comments for VeeamServers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam> VeeamServers
        {
            get
            {
                if ((this._VeeamServers == null))
                {
                    this._VeeamServers = base.CreateQuery<global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam>("VeeamServers");
                }
                return this._VeeamServers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam> _VeeamServers;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToUsers(global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser licenseUser)
        {
            base.AddObject("Users", licenseUser);
        }
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToGroups(global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup licenseGroup)
        {
            base.AddObject("Groups", licenseGroup);
        }
        /// <summary>
        /// There are no comments for UserGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToUserGroups(global::Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup licenseUserGroup)
        {
            base.AddObject("UserGroups", licenseUserGroup);
        }
        /// <summary>
        /// There are no comments for ManagedServers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToManagedServers(global::Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport managedSupport)
        {
            base.AddObject("ManagedServers", managedSupport);
        }
        /// <summary>
        /// There are no comments for VeeamServers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToVeeamServers(global::Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam veeam)
        {
            base.AddObject("VeeamServers", veeam);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Portal.LicenseMonitoringSystem.Users.Entities"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""LicenseUser"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""DisplayName"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""Enabled"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""LastLoginDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ManagedSupportId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""SamAccountName"" Type=""Edm.String"" />
        <Property Name=""Surname"" Type=""Edm.String"" />
        <Property Name=""UserType"" Type=""Portal.LicenseMonitoringSystem.Users.Entities.UserType"" Nullable=""false"" />
        <Property Name=""WhenCreated"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""IsDeleted"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""TenantId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""LicenseGroup"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" MaxLength=""256"" />
        <Property Name=""WhenCreated"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""IsDeleted"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""TenantId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""LicenseUserGroup"">
        <Key>
          <PropertyRef Name=""UserId"" />
          <PropertyRef Name=""GroupId"" />
        </Key>
        <Property Name=""UserId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""GroupId"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""ManagedSupport"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""DeviceId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Hostname"" Type=""Edm.String"" MaxLength=""200"" />
        <Property Name=""IpAddress"" Type=""Edm.String"" MaxLength=""39"" />
        <Property Name=""CheckInTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""ClientVersion"" Type=""Edm.String"" />
        <Property Name=""TenantId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""UserType"" IsFlags=""true"">
        <Member Name=""New"" Value=""0"" />
        <Member Name=""Active"" Value=""1"" />
        <Member Name=""Inactive"" Value=""2"" />
        <Member Name=""Central"" Value=""4"" />
        <Member Name=""ThirdParty"" Value=""8"" />
        <Member Name=""Admin"" Value=""16"" />
        <Member Name=""Service"" Value=""32"" />
        <Member Name=""Mailbox"" Value=""64"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Portal.LicenseMonitoringSystem.Veeam.Entities"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Veeam"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Edition"" Type=""Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseEditions"" Nullable=""false"" />
        <Property Name=""ExpirationDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""ExternalIpAddress"" Type=""Edm.String"" />
        <Property Name=""Hostname"" Type=""Edm.String"" />
        <Property Name=""HyperV"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""LicenseType"" Type=""Portal.LicenseMonitoringSystem.Veeam.Entities.LicenseTypeEx"" Nullable=""false"" />
        <Property Name=""ProgramVersion"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""SupportId"" Type=""Edm.String"" MaxLength=""50"" />
        <Property Name=""vSphere"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""IsDeleted"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""DeletionTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DeleterUserId"" Type=""Edm.Int64"" />
        <Property Name=""CheckInTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""ClientVersion"" Type=""Edm.String"" />
        <Property Name=""TenantId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""IsActive"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""LicenseEditions"">
        <Member Name=""Standard"" Value=""0"" />
        <Member Name=""Enterprise"" Value=""1"" />
        <Member Name=""EnterprisePlus"" Value=""2"" />
      </EnumType>
      <EnumType Name=""LicenseTypeEx"">
        <Member Name=""Empty"" Value=""0"" />
        <Member Name=""Evaluation"" Value=""1"" />
        <Member Name=""Full"" Value=""2"" />
        <Member Name=""NFR"" Value=""3"" />
        <Member Name=""Perpetual"" Value=""4"" />
        <Member Name=""Rental"" Value=""5"" />
        <Member Name=""Subscription"" Value=""6"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Users"" EntityType=""Portal.LicenseMonitoringSystem.Users.Entities.LicenseUser"" />
        <EntitySet Name=""Groups"" EntityType=""Portal.LicenseMonitoringSystem.Users.Entities.LicenseGroup"" />
        <EntitySet Name=""UserGroups"" EntityType=""Portal.LicenseMonitoringSystem.Users.Entities.LicenseUserGroup"" />
        <EntitySet Name=""ManagedServers"" EntityType=""Portal.LicenseMonitoringSystem.Users.Entities.ManagedSupport"" />
        <EntitySet Name=""VeeamServers"" EntityType=""Portal.LicenseMonitoringSystem.Veeam.Entities.Veeam"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
